language: python
python:
- '2.7'
- pypy-5.3.1
before_install:
- date
install:
- pip install .
- pip install -r requirements.txt
script: py.test
env:
  global:
  - secure: pwRKtlFQCTV2kSP32sCykKVD4wW0IudFduG1C3IQ4nqWURRVr7klKvp/Dkmr62gvcTk5xKgpuzVqHGAd01L6dWjBncOZmAu9Kx2rU+k3PXNdYLn9GvjA0OZ5IWqF8V5/XIQP1R8qAEX27vMdy5wtUy3vBGDpvPLhrKR4/CGRLpu5opH2bvYgkSk+oclvWbhUrCa9OEbrHHqxna4jZppINGSP2LjVA4k3KJheSJauSHTvbWbVWaaKviuxJBmCaPncumcBefxoy4oDQdNC+RVSzUg+3prv83F5wCIl/t7fihrzTupyfVs7YzpGEStPdO+3mgRG6bkQZKE7g56fNlzpzon9PLR1uluBco44+LMn2q5Y9LqXwrX2+hikF79FXALPZbE4RDmX5ZHttjfNSbQXIlFTAlvTKlXdPpszQl9zfXFljU1ZwTzdQYHAJS6xf2pKSxCFrLJgOJascFyI1EVClco/90U/ZscGYK4cQtBY8nMHFlnsI2Nl4a6PDmjNR4H8XC7WH74oBFhB9IxXqgsQYpd8eMNT7cBHaTkI0firW+9ZnMZn3kGUidjRkSOM1POSKir0jiV6uXn5LMjT91dg2ZcHvtALaGVqEBckalk0d8bBE13NbDmK7NPQ/PmiVQmcndkWA9q5BB90rvJ5Ox07kdyrsWH8r3nsteJgl7wlSFI=
  - secure: IlbH9DIsdwlDiyvEA+desO6gYn/jxyTo78xJKuAJViJOIvgUFS7EGfuCFDIhcCaM+d8OwLjKC/9woJOV29tK3OgoItgFVNyt9ENC4vFdZSrzpo48kBIQgbA/amH1NTbNa/VEaPz38BiKqj0ZJDZ4LWfT2gbR1h0wGK5172q7pnfn9En9yAZ+UefIsnWCog0cwyaxK2390ytAnQTW0CPzzZ6tjCbVrDLB1j/np9KUvzav9lWRer+Yw4HqNHVFCPC31NztHdyono36ATYq8FO6Wy+wa0xr5kgb3RD9mVxJsgN/0tlyg6V0w/BYvjCUH3OlDeeJUqWBPO1Jh3rXx9wbYznsjc4a4BwDe0Hy+DNhWpvaTHOeIRfiSzP2TPUYmrf/7VxGCh1ojdE8Xtauz/Taw14CObLrWCFwhWiIveS8yox7sWCEQzDpDjneBa7XdlZaCr5cfuq1RqcgzUImo5RV3Sex7CCRuNOTDJXgEz9BfCzgWBD/uWH2KKRWEHDtY+9qQogcmfGS426HCmaiQDnIQvuuiEQcWm1Z4cpn2eMgYElLMXN5tlBIRigkpJ5d4JuqsZpNJQ4ZT+GGLwlcI1QtozaaxsA+VCpZJloYWgfLjw8EGNb5WCPN5GuGWyG3mAR7roGWaEo/67Ykld5Hfwsntg8U+Px2UznrAAhWf9NyPkA=
